enyo.depends(
    "$lib/onyx/",
    "$lib/onyx/source/wip-package.js",
    "$lib/layout/",
    "$lib/layout/panels",
    "$lib/../parseData.js",
    "$lib/../transformData.js",
    "$lib/../Storage.js",
    "$lib/../EntryItem.js",
    "$lib/../ServiceItem.js",
    "$lib/../app.js",
    "$lib/../../css/app.css"
);